<?php

    class BaseDeDatos {
        // Reemplazar # por tus datos...
        public static $datos = "mysql:host=localhost;dbname=id6956846_juego"; // Nombre de la base de datos...
        public static $user = "id6956846_facundovega"; // Nombre del usuario de la base de datos...
        public static $pass = "cartasmarcadas"; // Contraseña de la base de datos...
        public static $url = "https://horaciovega1991.000webhostapp.com/assets/api/login"; // Nombre del dominio...
    }

?>